#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DVI-D-0 -d 5 6 7 8
bspc monitor HDMI-0 -d 1 2 3 4

bspc config border_width         2
bspc config window_gap          15
bspc config focused_border_color "#686868"

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Autostart Script
 
~/.config/bspwm/autostart &

