[window]
opacity = 0.75
padding = { x = 15, y = 15 }
decorations = "none"

# Font config:
[font]
normal = { family = "Terminess Nerd Font Mono", style = "Regular" }

[general]
import = ["/home/poptart/.cache/wal/colors-alacritty.toml"]
